# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shed < Formula
  desc "Easily manage Go tool dependencies"
  homepage ""
  version "0.5.1"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cszatmary/shed/releases/download/v0.5.1/shed_0.5.1_Darwin_x86_64.tar.gz"
      sha256 "8f5752e2510663fceb76c3b923b8f6551be5492813b619018edfd5ac4f153874"
    end
    if Hardware::CPU.arm?
      url "https://github.com/cszatmary/shed/releases/download/v0.5.1/shed_0.5.1_Darwin_arm64.tar.gz"
      sha256 "60804c1b8b31f032add90c1847f5d405b0b6580155878c8f3245e84f18cd5dfd"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cszatmary/shed/releases/download/v0.5.1/shed_0.5.1_Linux_x86_64.tar.gz"
      sha256 "5c7496589f32b6dc57b609bc347671d8ae5035423b41a5f3d25591b243415767"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/cszatmary/shed/releases/download/v0.5.1/shed_0.5.1_Linux_armv6.tar.gz"
      sha256 "c6c66a394f87e03f423f0952b94b0596e40a2cfbd2a56f9f61ca07a652cd2138"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cszatmary/shed/releases/download/v0.5.1/shed_0.5.1_Linux_arm64.tar.gz"
      sha256 "3b2d67a5d60972ddf528ff59d23eaed277317f08fa3aa1228faa70b9ad2aef22"
    end
  end

  def install
    bin.install "shed"
    bash_completion.install "completions/shed.bash"
    zsh_completion.install "completions/_shed"
  end

  test do
    system "#{bin}/shed --version"
  end
end
